### ISSUE TITLE
Connection Failed?

### ISSUE THREAD

**Issue by suzu42069** [SebastianLiando/bomb-party-assistant#6]
I've got the program to run but it doesn't seem to connect to the game server. 
I put in the Lobby code and it gets automatically disconnected. 
Any help? 
![Capture](https://user-images.githubusercontent.com/63757000/145015469-569cf8ce-2f09-43da-8330-caa852c011b7.PNG)

**Comment by SebastianLiando** [comment]
Your google chrome version (95.0.4638) and the driver's version (92) do not match.

Download the driver [here](https://chromedriver.chromium.org/home). Make sure the version matches your Google Chrome version. Then replace the one in `src/main/resources`.
